"""user add fields

Revision ID: 32348e7b55d9
Revises: 38eb0b088890
Create Date: 2019-01-06 22:17:14.992929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32348e7b55d9'
down_revision = '38eb0b088890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
